### ISSUE TITLE
Add support for Peggle Nights Steam version

### ISSUE THREAD

**Issue by GGuyX** [IntelOrca/PeggleEdit#27]
If possible, could you please add support for Peggle Nights Steam version? This is just a request so if you choose not to do it, that's fine :)

Currently, when trying to launch Peggle Night's executable via the program (using Steam version of the game), the following message gets shown:
![image](https://github.com/IntelOrca/PeggleEdit/assets/142028287/2b0ecc70-bb5b-4fb6-8eb6-52351a86d048)

**Comment by Moses2525** [comment]
Unfortunately that's a problem with how the steam version of Peggle & Peggle Nights is set up. if you start up either directly, you will get the same error. 

However this can be fixed by takeing Steam.dll, which is found in your steam installation folder.
![Delete](https://github.com/IntelOrca/PeggleEdit/assets/77868872/32bbbae5-ab04-4ea3-b6d8-2be2fb4f6d02)

And copying it to the install folder of Peggle Nights
![Delete1](https://github.com/IntelOrca/PeggleEdit/assets/77868872/ece2f1ee-a13b-428b-904c-b135a9f5b843)

![Delete2](https://github.com/IntelOrca/PeggleEdit/assets/77868872/043c5c17-618c-4028-b368-dfb2d07fd210)


afterwards it should look something like this:
![image](https://github.com/IntelOrca/PeggleEdit/assets/77868872/2f39b90d-5cce-436b-9bf3-525f75abc22b)

**Comment by GGuyX** [comment]
Thank you! This is an pretty useful workaround which I did know about for other games in the past in general but somehow forgot about. I will just close this issue if it's not something that Orca themselves can fix, but once again, I do greatly appreciate this!
